added imgeewidget
hasgeek/baseframe pull request #316
Opened 2020-08-14 10:36 UTC by iambibhas

2020-10-15 13:34 UTC, jace requested changes
The iframe rendering needs more elegance.

2020-10-15 13:34 UTC, jace commented on baseframe/forms/widgets.py
> +        )
Shouldn't this be returning the iframe?

2020-10-15 13:34 UTC, jace commented on baseframe/templates/baseframe/mui/forms.html.jinja2
> +                  {{ field.iframe }}
This `field.iframe` is patched in by the rendering of the field a few lines up. This is shaky. You should instead use `field(iframe=True)` and process that in the widget's `__call__` to return the iframe.

2020-10-22 06:49 UTC, vidya-ram approved these changes

2020-10-22 07:26 UTC, jace approved these changes
Two sentence fixes, all okay otherwise.

2020-10-22 07:26 UTC, jace commented on baseframe/forms/widgets.py
> +            raise ValueError("No imgee server specified")
"No Imgee server specified in config var IMGEE_HOST" (so that the dev knows what var to fix without looking at this source)

2020-10-22 07:26 UTC, jace commented on baseframe/templates/baseframe/mui/imgeefield.html.jinja2
> +<a href="#imgee-{{field.id}}" rel="modal:open" class="mui-btn mui-btn--raised imgee__button">{% trans %}Select or Upload Image{% endtrans %}</a>
Sentence case: "Select or upload image"

2020-10-27 07:08 UTC, merged